import type { CategoryId, CategoryBannerItem } from '../pages/Home/types';

const banners: CategoryBannerItem[] = [
  {
    id: 'women-01',
    category: 'women',
    type: 'image',
    src: '/src/assets/images/categories/women.webp',
    eyebrow: 'WOMEN / 2026',
    title: 'فراتر از زیبایی، یک امضا.',
    description: 'استایلی که قبل از شما وارد می‌شود.',
    href: '/category/women',
    objectPosition: 'center 30%',
  },
  {
    id: 'women-02',
    category: 'women',
    type: 'image',
    src: '/src/assets/images/categories/women.webp',
    eyebrow: 'WOMEN / 2026',
    title: 'Elegance has no season.',
    description: 'تعریف دوباره‌ی ظرافت.',
    href: '/category/women',
    objectPosition: 'center 30%',
  },
  {
    id: 'women-03',
    category: 'women',
    type: 'image',
    src: '/src/assets/images/categories/women.webp',
    eyebrow: 'WOMEN / 2026',
    title: 'تعریف دوباره‌ی ظرافت.',
    description: 'استایلی که قبل از شما وارد می‌شود.',
    href: '/category/women',
    objectPosition: 'center 30%',
  },
  {
    id: 'men-01',
    category: 'men',
    type: 'image',
    src: '/src/assets/images/categories/men.webp',
    eyebrow: 'MEN / 2026',
    title: 'استایل، زبان شخصیت است.',
    description: 'Defined by character.',
    href: '/category/men',
    objectPosition: 'center 30%',
  },
  {
    id: 'men-02',
    category: 'men',
    type: 'image',
    src: '/src/assets/images/categories/men.webp',
    eyebrow: 'MEN / 2026',
    title: 'Defined by character.',
    description: 'کلاسیک، اما نه معمولی.',
    href: '/category/men',
    objectPosition: 'center 30%',
  },
  {
    id: 'men-03',
    category: 'men',
    type: 'image',
    src: '/src/assets/images/categories/men.webp',
    eyebrow: 'MEN / 2026',
    title: 'کلاسیک، اما نه معمولی.',
    description: 'استایل، زبان شخصیت است.',
    href: '/category/men',
    objectPosition: 'center 30%',
  },
  {
    id: 'bags-01',
    category: 'bags',
    type: 'image',
    src: '/src/assets/images/categories/bag.webp',
    eyebrow: 'BAGS / 2026',
    title: 'Carry your signature.',
    description: 'جزئیات، امضای لوکس بودن.',
    href: '/category/bags',
    objectPosition: 'center 40%',
  },
  {
    id: 'bags-02',
    category: 'bags',
    type: 'image',
    src: '/src/assets/images/categories/bag.webp',
    eyebrow: 'BAGS / 2026',
    title: 'جزئیات، امضای لوکس بودن.',
    description: 'زیبایی که از مد عبور می‌کند.',
    href: '/category/bags',
    objectPosition: 'center 40%',
  },
  {
    id: 'bags-03',
    category: 'bags',
    type: 'image',
    src: '/src/assets/images/categories/bag.webp',
    eyebrow: 'BAGS / 2026',
    title: 'زیبایی که از مد عبور می‌کند.',
    description: 'Carry your signature.',
    href: '/category/bags',
    objectPosition: 'center 40%',
  },
  {
    id: 'shoes-01',
    category: 'shoes',
    type: 'image',
    src: '/src/assets/images/categories/Shoes.webp',
    eyebrow: 'SHOES / 2026',
    title: 'قدم‌هایت را به یادماندنی کن.',
    description: 'Walk your way.',
    href: '/category/shoes',
    objectPosition: 'center 40%',
  },
  {
    id: 'shoes-02',
    category: 'shoes',
    type: 'image',
    src: '/src/assets/images/categories/Shoes.webp',
    eyebrow: 'SHOES / 2026',
    title: 'Walk your way.',
    description: 'هنر حرکت کردن.',
    href: '/category/shoes',
    objectPosition: 'center 40%',
  },
  {
    id: 'shoes-03',
    category: 'shoes',
    type: 'image',
    src: '/src/assets/images/categories/Shoes.webp',
    eyebrow: 'SHOES / 2026',
    title: 'هنر حرکت کردن.',
    description: 'قدم‌هایت را به یادماندنی کن.',
    href: '/category/shoes',
    objectPosition: 'center 40%',
  },
  {
    id: 'accessories-01',
    category: 'accessories',
    type: 'image',
    src: '/src/assets/images/categories/accessories.webp',
    eyebrow: 'ACCESSORIES / 2026',
    title: 'جزئیات، همه چیز است.',
    description: 'Make it yours.',
    href: '/category/accessories',
    objectPosition: 'center 40%',
  },
  {
    id: 'accessories-02',
    category: 'accessories',
    type: 'image',
    src: '/src/assets/images/categories/accessories.webp',
    eyebrow: 'ACCESSORIES / 2026',
    title: 'Make it yours.',
    description: 'کم، اما تاثیرگذار.',
    href: '/category/accessories',
    objectPosition: 'center 40%',
  },
  {
    id: 'accessories-03',
    category: 'accessories',
    type: 'image',
    src: '/src/assets/images/categories/accessories.webp',
    eyebrow: 'ACCESSORIES / 2026',
    title: 'کم، اما تاثیرگذار.',
    description: 'جزئیات، همه چیز است.',
    href: '/category/accessories',
    objectPosition: 'center 40%',
  },
];

export function getRandomCategoryBanner(
  category: CategoryId,
  excludeId?: string,
): CategoryBannerItem {
  const filtered = banners.filter(
    (banner) =>
      banner.category === category && banner.id !== excludeId,
  );

  if (filtered.length === 0) {
    return banners.find((banner) => banner.category === category) ?? banners[0];
  }

  return filtered[Math.floor(Math.random() * filtered.length)];
}
